<a href="https://colab.research.google.com/github/mikhail-mat/rl-intro-sutton-barto/blob/main/n_armed_bandits.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [116]:
import numpy as np
import pandas as pd

In [117]:
np.random.seed(42)

In [118]:
n = 10 # number of actions

In [119]:
q = np.random.standard_normal(10) # true values for each action

In [120]:
q

array([ 0.49671415, -0.1382643 ,  0.64768854,  1.52302986, -0.23415337,
       -0.23413696,  1.57921282,  0.76743473, -0.46947439,  0.54256004])

In [121]:
# note that action 6 (index 5) with the value 1.579.. is the optimal action

In [122]:
Q_greedy = np.zeros(10)
Q_eps_greedy = np.zeros(10)

In [123]:
Q_greedy

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [124]:
k_greedy = np.zeros(10)
k_eps_greedy = np.zeros(10)

In [125]:
def give_reward(action_idx):
  noise = np.random.normal()
  reward = q[action_idx] + noise
  return reward

In [126]:
def find_optimal_action_idx(estimates):
  idx_of_highest_estimates = []
  highest = np.max(estimates)
  for i in range(10):
    if estimates[i] == highest:
      idx_of_highest_estimates.append(i)
  return idx_of_highest_estimates

In [127]:
def choose_greedy_action():
  idx_of_highest_estimates = find_optimal_action_idx(Q_greedy)
  greedy_action = np.random.choice(idx_of_highest_estimates)
  return greedy_action

In [128]:
def choose_eps_greedy_action():
  idx_of_highest_estimates = find_optimal_action_idx(Q_eps_greedy)
  greedy_action = np.random.choice(idx_of_highest_estimates)
  random_action = np.random.randint(10)
  action = np.random.choice([greedy_action, random_action], p=[0.9, 0.1])
  return action

In [129]:
greedy_action_history = []
eps_greedy_action_history = []

for i in range(10000):
  # greedy
  action = choose_greedy_action()
  reward = give_reward(action)
  greedy_action_history.append(int(action))

  k_greedy[action] += 1
  Q_greedy[action] += (1/k_greedy[action])*(reward - Q_greedy[action])

  # epsilon-greedy
  action = choose_eps_greedy_action()
  reward = give_reward(action)
  eps_greedy_action_history.append(int(action))

  k_eps_greedy[action] += 1
  Q_eps_greedy[action] += (1/k_eps_greedy[action])*(reward - Q_eps_greedy[action])

In [130]:
Q_greedy

array([ 0.        ,  0.        ,  0.        ,  0.        , -0.15769045,
        0.        ,  0.        ,  0.77631321,  0.        ,  0.        ])

In [131]:
Q_eps_greedy

array([ 0.68742081, -0.03613479,  0.64215852,  1.51735308, -0.20854931,
       -0.15168015,  1.50341098,  0.8795422 , -0.48190138,  0.68635277])

In [132]:
print(greedy_action_history)

[4, 4, 4, 4, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 

In [133]:
print(eps_greedy_action_history)

[8, 8, 8, 8, 2, 2, 2, 8, 8, 9, 8, 8, 9, 9, 9, 9, 9, 9, 9, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 1, 9, 3, 3, 3, 3, 3, 3, 3, 3, 3, 5, 3, 3, 3, 2, 3, 9, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 9, 3, 3, 3, 3, 3, 9, 3, 3, 3, 3, 3, 7, 3, 3, 3, 4, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 1, 3, 3, 3, 6, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 8, 3, 4, 3, 3, 3, 3, 5, 3, 2, 3, 3, 3, 9, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 5, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 9, 3, 3, 3, 4, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 5, 3, 3, 3, 3, 3, 3, 3, 0, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 7, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 7, 3, 5, 3, 3, 3, 8, 3, 3, 3, 3, 3, 3, 3, 3, 1, 3, 3, 3, 3, 3, 3, 2, 4, 3, 3, 3, 3, 4, 3, 3, 3, 3, 5, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 3, 3, 3, 3, 7, 3, 6, 3, 3, 