<a href="https://colab.research.google.com/github/mikhail-mat/rl-intro-sutton-barto/blob/main/n_armed_bandits.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [194]:
import numpy as np
import pandas as pd

In [195]:
np.random.seed(42)

In [196]:
n = 10 # number of actions

In [197]:
q = np.random.standard_normal(10) # true values for each action

In [198]:
q

array([ 0.49671415, -0.1382643 ,  0.64768854,  1.52302986, -0.23415337,
       -0.23413696,  1.57921282,  0.76743473, -0.46947439,  0.54256004])

In [199]:
# note that action 6 (index 5) with the value 1.579.. is the optimal action

In [200]:
Q_greedy = np.zeros(10)
Q_eps_greedy = np.zeros(10)
Q_ucb = np.zeros(10)
ucb_terms = np.zeros(10)
c = 2

In [201]:
Q_greedy

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [202]:
k_greedy = np.zeros(10)
k_eps_greedy = np.zeros(10)
k_ucb = np.zeros(10)

In [203]:
def give_reward(action_idx):
  noise = np.random.normal()
  reward = q[action_idx] + noise
  return reward

In [204]:
def find_optimal_action_idx(estimates):
  idx_of_highest_estimates = []
  highest = np.max(estimates)
  for i in range(10):
    if estimates[i] == highest:
      idx_of_highest_estimates.append(i)
  return idx_of_highest_estimates

In [205]:
def choose_greedy_action():
  idx_of_highest_estimates = find_optimal_action_idx(Q_greedy)
  greedy_action = np.random.choice(idx_of_highest_estimates)
  return greedy_action

In [206]:
def choose_eps_greedy_action():
  idx_of_highest_estimates = find_optimal_action_idx(Q_eps_greedy)
  greedy_action = np.random.choice(idx_of_highest_estimates)
  random_action = np.random.randint(10)
  action = np.random.choice([greedy_action, random_action], p=[0.9, 0.1])
  return action

In [207]:
def choose_ucb_action():
  unvisited = np.where(k_ucb == 0)[0]
  if len(unvisited) > 0:
      return np.random.choice(unvisited)
  estimates = np.add(Q_ucb, ucb_terms)
  idx_of_highest_estimates = find_optimal_action_idx(estimates)
  ucb_action = np.random.choice(idx_of_highest_estimates)
  return ucb_action

In [208]:
t = 0 # timestep

greedy_total_reward = 0
eps_greedy_total_reward = 0
ucb_total_reward = 0

for i in range(10000):
  t += 1

  # greedy
  action = choose_greedy_action()
  reward = give_reward(action)
  greedy_total_reward += reward

  k_greedy[action] += 1
  Q_greedy[action] += (1/k_greedy[action])*(reward - Q_greedy[action])

  # epsilon-greedy
  action = choose_eps_greedy_action()
  reward = give_reward(action)
  eps_greedy_total_reward += reward

  k_eps_greedy[action] += 1
  Q_eps_greedy[action] += (1/k_eps_greedy[action])*(reward - Q_eps_greedy[action])

  # UCB
  action = choose_ucb_action()
  reward = give_reward(action)
  ucb_total_reward += reward

  k_ucb[action] += 1
  Q_ucb[action] += (1/k_ucb[action])*(reward - Q_ucb[action])

  for j in range(10):
    if k_ucb[j] != 0:
      ucb_terms[j] = c*(np.log(t) / k_ucb[j])**0.5


In [209]:
Q_greedy

array([ 0.        ,  0.        ,  0.        ,  1.51654537, -0.1849809 ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ])

In [210]:
greedy_total_reward

np.float64(15160.349140347298)

In [211]:
Q_eps_greedy

array([ 0.54051396, -0.11506662,  0.73755689,  1.52123516, -0.17100115,
       -0.34284718,  1.44840496,  0.6104569 , -0.41175406,  0.45724777])

In [212]:
eps_greedy_total_reward

np.float64(14097.358565278737)

In [213]:
Q_ucb

array([ 0.79604266, -0.31482053,  0.84277335,  1.51741721,  0.1538271 ,
       -0.12199137,  1.57846118,  0.85600871, -0.02388413,  0.79121573])

In [214]:
ucb_total_reward

np.float64(15385.608814935254)